### ISSUE TITLE
Wildcard matches for metadata behave strangely

### ISSUE THREAD

**Issue by stevenrbrandt** [agaveplatform/science-apis#9]
```
sbrandt:~/tmp/JetLag$ metadata-list -Q '{"name":"*"}'

sbrandt:~/tmp/JetLag$ metadata-list -Q '{"name":"systems*"}'
5980953615272570390-242ac11d-0001-012
4655096387154743786-242ac11d-0001-012
sbrandt:~/tmp/JetLag$ metadata-list -V 5980953615272570390-242ac11d-0001-012
Calling curl -sk -H "Authorization: Bearer 58b6c1931d7829f42e20b64b5b4f2489" 'https://sandbox.agaveplatform.org/meta/v2/data/5980953615272570390-242ac11d-0001-012?pretty=true'
{
  "status" : "success",
  "message" : null,
  "version" : "2.2.6-r4f1bf09",
  "result" : {
    "uuid" : "5980953615272570390-242ac11d-0001-012",
    "owner" : "sbrandt",
    "schemaId" : null,
    "internalUsername" : null,
    "associationIds" : [ ],
    "lastUpdated" : "2019-12-05T13:44:39.814-06:00",
    "name" : "system-config-sbrandt-shelob",
...
```

**Comment by stevenrbrandt** [comment]
Notice that I query for "systems*" but "system-config-sbrandt-shelob" matches, which it shouldn't.

**Comment by deardooley** [comment]
Copying the Slack thread here for closure:

A valid query that would return all metadata entries starting with systems would be:
```
metadata-list -Q '{"name":"systems.*"}'
```
A valid query that would return all metadata entries would be:
```
metadata-list -Q '{"name":".*"}'
```
Note that this is the same as just running without specifying a query. An argument could be made to change the parsing of the `*` in the search expression to mean `.*`, but that would break the semantics of the regex pattern matching, which for the limited scope that the mongo search supports, would effectively break grouping and most partial matching behavior.

To see the impact of various queries, you can use the regex planet generator. Here are some test strings relevant to what you originally asked about.  https://www.regexplanet.com/share/index.html?share=yyyyd4hnx6r

The other side of the argument is that the rest of the api natively supports simple `*` wildcards in the search.

The idea being that the metadata api had a different search semantics than the rest of the apis (standard mongo query semantics), so it was ok to diverge. I guess there is value in consistency, though i think we would have to expand the query syntax to support custom handling of missing fields, nested wildcards, etc. My guess is that it would scale poorly, but I'm open to discussion.
